ingress:
  - hostname: thegrandprinterofmemesandunfinitetodosservanttonox.tech
    service: http://caddy:80
  - hostname: bibliothek.thegrandprinterofmemesandunfinitetodosservanttonox.tech
    service: http://caddy:80
  - service: http_status:404
