ingress:
  - hostname: thegrandprinterofmemesandunfinitetodosservanttonox.tech
    service: http://caddy:80
  - hostname: bibliothek.thegrandprinterofmemesandunfinitetodosservanttonox.tech
    service: http://caddy:80
  - hostname: bio.thegrandprinterofmemesandunfinitetodosservanttonox.tech
    service: http://caddy:80
  - hostname: bioapi.thegrandprinterofmemesandunfinitetodosservanttonox.tech
    service: http://caddy:80
  - hostname: ocr.thegrandprinterofmemesandunfinitetodosservanttonox.tech
    service: http://caddy:80
  - hostname: watch.thegrandprinterofmemesandunfinitetodosservanttonox.tech
    service: http://caddy:80
  - service: http_status:404
